
import json

prefix = "Hey Love,\nA very Good morning to you babu.\n\n"
suffix = "\n\nI love you a lot."

messages = [
    "Waking up and knowing you're mine feels like the universe's greatest gift to me. Every sunrise reminds me how blessed I am to love you.",
    "The sun may rise for the world, but my heart only truly awakens when I think of you. You are my first thought, my sweetest dream, and my beautiful reality.",
    "I hope your coffee is as warm as my feelings for you and your day as sweet as your smile. You make every ordinary moment feel extraordinary.",
    "Every morning is a blank canvas, and the first thing I want to paint on it is your beautiful name. You are the art my heart creates without even trying.",
    "You are the poetry I could never find the words for, until you walked into my life and became every verse I needed. Missing you already.",
    "Sending you the warmth of my embrace through these words, wrapped in all the love my heart holds for you. May your day be as beautiful as you are to me.",
    "You're the dream I never want to wake up from and the reality I'm endlessly grateful for. Being yours is my favorite thing in this world, darling.",
    "Rise and shine, my beautiful. The world is waiting for the magic that only you can create. And I'm here, loving you more with each passing moment.",
    "I hope your day unfolds as gently and beautifully as your smile does when you look at me. You make everything better just by existing.",
    "Just a soft whisper to start your day: you are loved beyond words, cherished beyond measure, and missed more than you know.",
    "May today wrap you in the same kindness and tenderness that you bring into my life every single day. You deserve all the beautiful things, babu.",
    "Waking up is my favorite part of the day because it means another 24 hours of loving you, missing you, and being grateful you're mine.",
    "You are my clarity when the world feels chaotic, my calm in every storm. Thank you for being my safe place, my peace.",
    "The morning light is beautiful, but it pales in comparison to the radiance you bring to my life. You're my brightest star, always.",
    "Even though we're apart right now, I hope you can feel my arms around you, holding you close in spirit. You're always with me, in my heart.",
    "May your day be sprinkled with little miracles and your heart filled with joy. You deserve nothing less than magic, my beautiful soul.",
    "You are the melody that plays in my heart from sunrise to sunset. Every beat, every rhythm belongs to you, darling.",
    "Open your eyes to this new day and know that someone is thinking of you with the biggest smile. You make being amazing look so effortless, babu.",
    "Thank you for being the reason behind every smile that touches my lips, every joy that fills my heart. You complete me in ways I never knew I needed.",
    "I hope today brings you even a fraction of the happiness and love you've poured into my life. You deserve the entire universe, my darling.",
    "Remember, you are capable of achieving anything you set your beautiful mind to. I believe in you today and always, my wonderful girl.",
    "Sending you strength to face whatever challenges come your way and endless love to keep your heart warm. You've got this, and you've got me.",
    "You are hands down the best decision my heart has ever made. Loving you feels like coming home, every single time.",
    "Let this morning remind you of how incredibly precious you are to me, how deeply you're loved, and how much you mean to my world.",
    "My day begins and ends with thoughts of you, with gratitude for having you in my life. You are my everything, my always.",
    "May the sun warm your beautiful face and my love warm every corner of your heart today. You're forever cherished, babu.",
    "You have this magical way of making even the most ordinary moments feel like something extraordinary. That's your power over my heart.",
    "I hope the day ahead treats you with gentleness and fills your hours with sweetness, just like the thought of you fills my heart.",
    "You are my safe harbor in this vast, unpredictable world. With you, I've found my peace, my home, my forever.",
    "Every sunrise is beautiful, but your love is the greatest blessing my life has ever known. You are my miracle, darling.",
    "I'm rooting for you today and every day, cheering you on from the depths of my heart. You're going to do amazing things, my love.",
    "Let your beautiful soul shine as brilliantly as the morning sun. The world needs your light, and I need your love.",
    "You are the thought that calms my restless mind and the fire that warms my heart. You are everything I never knew I always needed.",
    "Wishing you a day free of worries and overflowing with love, laughter, and all the things that make your heart smile.",
    "If I could reach up and bring you the stars from the sky, I would. But for now, I offer you my heart—it's all yours, always.",
    "May you find beauty in the smallest moments today—a warm cup of tea, a gentle breeze, a kind word. You deserve every bit of joy.",
    "You are my favorite hello and my hardest goodbye. Every moment with you is a treasure I hold close to my heart.",
    "Words feel insufficient to express how much I love you, how deeply you've touched my soul. You are my heart's language, babu.",
    "Your happiness is my mission today and every day. Seeing you smile is the greatest reward I could ever ask for.",
    "Sending you the warmest virtual hug to start your day. Imagine my arms around you, holding you close, never wanting to let go.",
    "You inspire me every day to be kinder, stronger, and better. Thank you for making me want to be the best version of myself.",
    "May the day ahead be as stunning, graceful, and absolutely breathtaking as you are. You outshine every star in my sky.",
    "There is no one else I would rather share this beautiful, messy, wonderful life with. You are my choice, my love, my forever.",
    "You are the sunshine that never fades, the warmth that never leaves. Even on the cloudiest days, you brighten my world.",
    "Take a deep breath, my strong and beautiful girl. You are far stronger and more capable than you give yourself credit for.",
    "I hope you dance through your day with a light heart and a joyful spirit. You make life feel like a beautiful celebration.",
    "My love for you grows deeper with every sunrise, stronger with every heartbeat. You are my endless forever, darling.",
    "Thinking of you is the sweetest way to start my day. You fill my mind with warmth and my heart with an indescribable joy.",
    "You are the missing piece of my soul that I didn't even know I was searching for. Now that I've found you, I'm complete.",
    "May your path today be clear, your burdens light, and your heart full of all the love I'm sending your way.",
    "I am so incredibly proud of the person you are—your kindness, your strength, your beautiful heart. You amaze me every day.",
    "Every morning I wake up and count my blessings, and you're always at the top of the list. I'm so lucky you're mine.",
    "You are the beautiful constant in my ever-changing life, the steady beat in my heart's rhythm. You are my anchor, my love.",
    "Wishing you a morning as peaceful and serene as a quiet dawn, filled with promise and gentle hope for the day ahead.",
    "Your smile is the only alarm clock my heart needs to wake up happy. Just the thought of you brightens my entire day.",
    "I hope today brings you one step closer to your dreams. Keep chasing them, my ambitious and beautiful girl. I'm right here cheering you on.",
    "Never forget: you are deeply loved, infinitely valued, and more than enough exactly as you are. You are perfect to me.",
    "May the morning light kiss your face as gently as I wish I could right now. You are forever in my thoughts, in my heart.",
    "Just a gentle reminder before you start your day: you've got this, you're incredible, and I believe in you completely.",
    "You turn my gray skies into the brightest blue, my cold nights into warm embraces. You are my sunshine, my everything.",
    "My heart races a little faster every time I think of you. You have this beautiful way of making me feel alive in the best way.",
    "I hope your coffee tastes like pure magic today, and your day unfolds with the same sweetness you bring into my life.",
    "You are the reason my reality has become more beautiful than any dream I could have ever imagined. You are my living dream.",
    "May serenity wrap around you like a soft blanket today, bringing you peace in every moment. You deserve all the calm and comfort.",
    "You are the masterpiece of my life, the most beautiful creation my heart has ever known. Every day with you is a work of art.",
    "Rise and shine, my lovely girl. The world is waiting for your unique spark, your special magic. Go out there and be amazing.",
    "I'm sending all my love to you on the wings of the morning breeze. May it find you and remind you how cherished you are.",
    "You are the first thought that graces my mind when I wake and the last prayer whispered by my heart before I sleep. You are my constant.",
    "May today be gentle with you, kind to your heart, and generous with its blessings. You deserve nothing but the best, always.",
    "I love who you are right now and who you're growing into. Watching you evolve is one of my greatest privileges and joys.",
    "You are my greatest adventure, my most thrilling journey. Every day with you is a new page in our beautiful story together.",
    "May your day flow as effortlessly as your natural beauty and grace. You make everything look so easy and elegant, babu.",
    "I carry your heart in mine, everywhere I go, in everything I do. We are connected in ways that words cannot fully capture.",
    "Wake up and conquer the day with your inherent grace and unstoppable spirit. You have everything you need within you, my strong girl.",
    "You are the sugar that sweetens my tea and the joy that flavors my life. Everything is better, sweeter, brighter with you.",
    "May laughter find you often today, filling your hours with lightness and your heart with pure happiness. Your laugh is my favorite sound.",
    "Every day with you becomes my new favorite page in the story of us. I can't wait to see what beautiful moments today will bring.",
    "I hope you feel absolutely incredible today—as incredible as you make me feel every single day just by being you.",
    "You are my home, no matter where we are, no matter the distance between us. My heart lives with you always.",
    "May the morning dew on the grass remind you that every day is a fresh start, a new beginning full of possibilities and hope.",
    "My love for you is as endless and vast as the sky above us, stretching beyond what the eye can see and the heart can measure.",
    "You possess this rare gift of making the simplest, most ordinary moments feel absolutely magical. That's the power of your love.",
    "Be gentle with yourself today, my darling. Treat yourself with the same kindness and compassion you so freely give to others.",
    "I hope the universe conspires in your favor today, opening doors and creating opportunities. You deserve all the stars aligning for you.",
    "You are the best part of every single day—the highlight of my mornings, afternoons, and nights. You are my always and forever.",
    "May your day be as vibrant and full of life as your beautiful spirit. You bring color to my world in ways I never knew existed.",
    "Knowing you're happy, knowing you're smiling somewhere in this world, that alone makes my day complete and my heart full.",
    "You are the calm that soothes my storm, the peace that quiets my chaos. With you, I've found my serenity, my safe haven.",
    "I hope you truly know, deep in your heart, just how cherished and loved you are. You mean the entire world to me, babu.",
    "May your steps be light today and your heart be heavy with the weight of all the love I'm sending across the distance to you.",
    "You are my happily ever after, my fairytale come true. Every moment with you is a dream I never want to wake up from.",
    "I hope today surprises you with unexpected moments of pure joy, little gifts from the universe just for you. You deserve all the happiness.",
    "You are the rhythm of my heart, the beat that keeps me alive. Without you, there would be no music in my life.",
    "Rise gently, my love. The day is yours to shape, to mold, to create. Make it as beautiful as you are, and I know it will be magnificent.",
    "Thank you for simply being you—authentic, beautiful, imperfectly perfect. You are exactly who I need, exactly who I love.",
    "May you find inspiration hiding in every corner today—in the sunrise, in a smile, in a moment of quiet reflection.",
    "You are the anchor that keeps me grounded when life gets overwhelming. With you, I always find my way back to center.",
    "I hope your day is filled with sweet little moments that make you smile—those tiny treasures that make life so precious.",
    "Loving you is the easiest, most natural thing I've ever done. It requires no effort, only the willingness to let my heart be yours.",
    "You make this sometimes harsh world feel softer, gentler, more bearable. Thank you for being my gentle soul, my tender heart.",
    "Today is a gift, just like you are a gift to my life. I'm unwrapping each moment with gratitude for having you.",
    "May confidence wrap around you like a cloak today, reminding you of your strength, your worth, your incredible capabilities.",
    "You are the guiding light that shows me the way home, the beacon that never fails to lead me back to where I belong—with you.",
    "I hope you smile a thousand times today, my beautiful girl. Each smile of yours is a gift to this world and a treasure to my heart.",
    "You are the reason I believe in love, in soulmates, in forever. You restored my faith in all things beautiful and true.",
    "May the day unfold for you like a beautiful flower, revealing its beauty petal by petal, moment by precious moment.",
    "My heart awakens each morning with only one purpose—to call your name, to think of you, to love you more deeply than yesterday.",
    "You are the miracle I get to wake up to every day, the blessing I never take for granted. You are my answered prayer.",
    "Focus on the good today, and I promise the good will find you too. You attract beautiful things because you are beautiful yourself.",
    "May your day strike the perfect balance—productive enough to feel accomplished, peaceful enough to feel rested. You deserve both.",
    "You are my favorite thought, the one my mind returns to in quiet moments, in busy moments, in every single moment in between.",
    "I hope you feel the warmth of the sun on your skin and know that my love for you burns even brighter and warmer.",
    "You make everything in my life make sense. The chaos becomes order, the confusion becomes clarity. You are my answer to everything.",
    "May kindness find you at every turn today—in the people you meet, in the moments you experience, in the universe's gentle embrace.",
    "You are the spark that ignites my passion, the flame that keeps my fire burning. You light up my entire world, darling.",
    "I hope your day is as wonderful and infectious as your laugh, as warm and comforting as your embrace. You are pure joy.",
    "You are my dawn and my dusk, my beginning and my end, my alpha and omega. You are my everything in between too.",
    "May you be surrounded by positivity and good energy today. Let it lift you up and carry you through whatever comes your way.",
    "There is genuine magic in your presence, in the way you move through the world. You enchant me completely, utterly, endlessly.",
    "You are the reason for my gratitude, the source of my joy, the foundation of my happiness. Thank you for being mine.",
    "I hope you achieve everything you set out to accomplish today. I have complete faith in your abilities and your beautiful determination.",
    "May peace be with you from the moment you wake until you drift back to sleep, wrapping you in comfort and tranquility.",
    "You are simply irreplaceable, one of a kind, completely unique. There could never be another you, and I wouldn't want there to be.",
    "I hope the day treats you like the queen you are—with respect, admiration, and the royal treatment you absolutely deserve.",
    "You are the heartbeat of my days, the pulse that keeps my life flowing with purpose and meaning. You are my vital rhythm.",
    "May your troubles be light as feathers and your blessings be heavy as gold. You deserve an abundance of good things, babu.",
    "You are the poem the universe wrote specifically for me, every word perfect, every line beautiful. You are my cosmic love letter.",
    "I hope you find time for yourself today—time to breathe, to reflect, to just be. You deserve moments of peace and self-care.",
    "You are the very essence of joy itself, the purest form of happiness I've ever known. You are joy personified, my love.",
    "May your heart be light as a feather today, unburdened by worry, lifted by love, carried by hope and beautiful possibilities.",
    "You are my forever and always, my eternal constant, my infinite love. There is no end to how much I cherish you.",
    "I hope today brings you closer to your heart's deepest desires and wildest dreams. Keep reaching for them, my ambitious girl.",
    "You are the most beautiful view my eyes have ever beheld. Looking at you, thinking of you, is my favorite sight in this world.",
    "May the day be as generous and giving as your beautiful heart. You give so much love—may it return to you tenfold.",
    "You are my inspiration, the muse that awakens my creativity and passion. Everything good I create, I create with you in mind.",
    "I hope you feel empowered today, strong and capable, ready to take on anything. You have incredible power within you, darling.",
    "You are the vibrant colors in my black and white world. Before you, everything was monochrome. Now, life is a beautiful rainbow.",
    "May you shine brighter than the sun today, illuminating everything and everyone around you with your natural radiance and warmth.",
    "You are my safe place, the shelter I run to when the world gets too loud, too harsh, too much. You are my sanctuary.",
    "I hope your day is filled with happy accidents and beautiful coincidences, those little serendipitous moments that make life magical.",
    "You are the love of my life, my soulmate, my everything. These aren't just words—they're the deepest truth of my heart.",
    "May the world be soft and gentle with you today. You deserve tenderness, kindness, and all the sweetness life has to offer.",
    "You are my morning glory, the beautiful bloom that greets me each day. You make every morning worth waking up to.",
    "I hope you feel refreshed, rejuvenated, and ready to embrace whatever this day brings your way. You've got this, my strong girl.",
    "You are the melody of my soul, the song my heart sings without words. You are my music, my harmony, my perfect note.",
    "May you walk in beauty today—finding it in nature, in kindness, in yourself. You are surrounded by beauty because you are beauty.",
    "You are everything I ever wanted and so much more than I ever dreamed possible. You exceed every expectation, every hope, every wish.",
    "I hope your day is as spectacular and breathtaking as you are. May it be filled with moments that take your breath away.",
    "You are the wind beneath my wings, the force that lifts me higher. With you, I feel like I can fly, like I can do anything.",
    "May you find joy not just in the destination but in every step of the journey today. Life with you is the most beautiful journey.",
    "You are my heart's greatest delight, the source of my deepest contentment. Simply knowing you exist makes my world brighter.",
    "I hope you can feel the waves of love I'm sending your way, crashing over you gently, reminding you how deeply you're cherished.",
    "You are the reason for every smile that graces my face, every laugh that escapes my lips. You are my happiness personified.",
    "May your day be sprinkled with sweet surprises and unexpected delights. You deserve all the wonderful things life has to offer.",
    "You are my compass, always pointing me in the right direction, guiding me through life's journey with your wisdom and love.",
    "I hope you conquer every mountain in your path today, big or small. You're stronger than you know, braver than you believe.",
    "You are the best part of me, the piece that makes me whole. Without you, I'm incomplete, but with you, I'm everything.",
    "May your spirit soar today, free and unburdened, reaching heights you never thought possible. You were made to fly, darling.",
    "You are my sweetest dream come true, the fantasy that became reality. You are proof that miracles exist and dreams do come true.",
    "I hope today unfolds like a masterpiece for you, each moment a brushstroke creating something beautiful and uniquely yours.",
    "You are the love song I never tire of, the melody I want to hear on repeat for the rest of my life. You are my eternal soundtrack.",
    "May you be wrapped in happiness today, cocooned in joy, surrounded by all the love you so generously give to others.",
    "You are my lucky charm, my four-leaf clover, my shooting star. With you in my life, I feel like the luckiest person alive.",
    "I hope you feel the sunshine not just on your skin but deep in your soul, warming you from the inside out with pure light and love.",
    "You are the joy of my morning, the peace of my afternoon, the comfort of my evening. You are my all-day, every-day happiness.",
    "May your day be as refreshing and invigorating as the morning breeze, bringing new energy and renewed hope with every moment.",
    "You are my stillness in the rush of life, the quiet calm in the midst of chaos. You bring me peace like nothing else can.",
    "I hope you find countless reasons to laugh today. Your laughter is the most beautiful sound in my world, pure music to my ears.",
    "You are the keeper of my heart, the guardian of my soul. I trust you with all that I am and all that I have.",
    "May all your efforts today blossom into beautiful results. I believe in the seeds you're planting and the harvest you'll reap.",
    "You are my daily miracle, the wonder I get to witness every single day. Never once have I taken you for granted, my precious gift.",
    "I hope your day is filled with grace—in your movements, in your words, in the moments that unfold before you. You embody grace itself.",
    "You are the light of my life, the flame that never dims, the glow that brightens even my darkest days. You illuminate everything.",
    "May you be touched by love today in countless small ways—a kind word, a warm gesture, a gentle reminder that you matter.",
    "You are my everything—my past, my present, my future. You are woven into every part of my existence, inseparable from who I am.",
    "I hope you feel as special, unique, and irreplaceable as you truly are. There is no one like you, and that's your superpower.",
    "You are the smile on my face, the joy in my heart, the spring in my step. You are the reason I move through life with happiness.",
    "May your day be as bright and sparkling as your beautiful eyes. You see the world with such wonder, such beauty—it's captivating.",
    "You are the warmth of my sun, the heat that keeps my heart burning with love and passion. You are my eternal summer, my endless warmth.",
    "I hope you have an absolutely fabulous day filled with moments that make you grateful to be alive, to be you, to be loved.",
    "You are the dream I'm living, the reality that surpasses every fantasy. Life with you is better than anything I could have imagined.",
    "May success follow you like a faithful companion today, walking beside you in every endeavor, celebrating every victory with you.",
    "You are my heart's true home, the place where I belong, where I'm most myself, where I'm most at peace. You are my forever residence.",
    "I hope your coffee is piping hot and your day is wonderfully cool and comfortable. May everything align perfectly for you today.",
    "You are the reason I rise each morning with purpose and hope. You give meaning to my days and dreams to my nights.",
    "May you be blessed with abundant joy today—joy in the big moments and joy in the quiet, simple ones too. You deserve it all.",
    "You are my favorite person in the entire world, my chosen one, my preferred companion in this journey called life.",
    "I hope you savor and enjoy every moment today, living fully, loving deeply, experiencing life in all its beautiful complexity.",
    "You are the song in my heart, the lyrics to my life, the music that makes everything more beautiful and meaningful.",
    "May your day be completely worry-free, unburdened by stress or anxiety. You deserve peace and tranquility in abundance.",
    "You are my precious gem, rare and valuable beyond measure. The world is richer, more beautiful, because you exist in it.",
    "I hope the day brings you peace in every form—peace of mind, peace of heart, peace in your soul. You deserve such serenity.",
    "You are the love I hold most dear, the treasure I guard most carefully, the gift I cherish most deeply.",
    "May you find clarity today in your thoughts, your decisions, your path forward. Trust yourself—you know the way, babu.",
    "You are my morning star, the first light I see, the guiding brightness that helps me navigate each new day with hope and love.",
    "I hope you feel cherished today in every interaction, in every moment, in every breath. You are treasured beyond words.",
    "You are the steady beat of my heart, the rhythm that keeps me alive. Without you, there would be no pulse, no life.",
    "May your day overflow with love in all its forms—romantic love, friendly love, self-love, universal love. Let it fill you completely.",
    "You are my sweet inspiration, the muse that awakens my creativity, my passion, my drive to be better every single day.",
    "I hope you have a wonderfully productive day, accomplishing goals and feeling that satisfying sense of achievement. You've got this!",
    "You are the one I adore with every fiber of my being, the person I worship with my whole heart and soul.",
    "May your day be as lovely, graceful, and beautiful as you are. May it mirror the elegance and charm you bring to the world.",
    "You are my happy place, the mental and emotional space I retreat to when I need comfort, joy, and unconditional love.",
    "I hope you feel the warm kiss of the sun on your skin today, and know that I wish I could be there to kiss you myself.",
    "You are the wish I made upon a star that actually came true. You are my granted wish, my answered prayer.",
    "May your day be filled with radiant light—the light of possibility, of hope, of love, of infinite potential.",
    "You are my true love, my real love, my authentic and genuine love. There's nothing fake or shallow about what I feel for you.",
    "I hope you share your beautiful smile with a stranger today and brighten their world the way you brighten mine every single day.",
    "You are the calmness I desperately need in this hectic, chaotic world. You are my zen, my tranquility, my peace.",
    "May your day be as sweet as honey, as smooth as silk, as precious as gold. You deserve all the finest things life offers.",
    "You are my guiding light through the darkness, the beacon that shows me the way when I'm lost, the star I navigate by.",
    "I hope you feel powerful today, strong and capable, ready to move mountains and achieve the impossible. You can do anything, babu.",
    "You are the reason I strive to be better, to do more, to reach higher. You inspire my best self every single day.",
    "May your day be full of promise and potential, with every hour bringing new opportunities and beautiful possibilities.",
    "You are my heart's deepest desire, the longing that finally found its fulfillment. I found what I was searching for in you.",
    "I hope you have a truly magical day, filled with wonder, enchantment, and those special moments that feel like pure magic.",
    "You are hands down the best thing that has ever happened to me. You transformed my life in the most beautiful ways.",
    "May your day be completely free of stress and tension. May everything flow smoothly and effortlessly for you today.",
    "You are my eternal love, the forever kind of love that transcends time and space. You are my always and my infinity.",
    "I hope you see beauty everywhere you look today—in nature, in people, in moments, in yourself. You are surrounded by beauty.",
    "You are the calm after my storm, the peace that follows the chaos. You bring order to my disorder, serenity to my turmoil.",
    "May your day be as bright and radiant as your smile, which lights up my entire world and makes everything better.",
    "You are my soulmate, the person my soul recognizes and connects with on the deepest level. We were meant to find each other.",
    "I hope you feel like the star you are today—shining brightly, standing out beautifully, illuminating the world around you.",
    "You are the reason I believe in magic, in miracles, in the impossible becoming possible. You made me a believer again.",
    "May your day be filled with genuine laughter that comes from deep within your soul and brightens everything around you.",
    "You are my endless love, the kind that has no beginning and no end, that simply exists eternally and unconditionally.",
    "I hope you have a wonderfully peaceful day, filled with quiet moments of contentment and gentle happiness.",
    "You are the joy of my entire life, the source of my happiness, the reason my heart sings with gladness every day.",
    "May your day be as authentic and genuine as you are. Never change who you are—you're perfect just as you are.",
    "You are my morning bliss, the perfect way to start each day. Thinking of you is the sweetest wake-up call.",
    "I hope you feel the love of the universe surrounding you today, holding you, supporting you, celebrating you.",
    "You are the reason I wake with purpose each morning, eager to see what the day brings, excited to live and love fully.",
    "May your day be full of wonder and awe, those beautiful moments that remind you how magical life can be.",
    "You are my sweet escape from reality, my beautiful daydream, my perfect fantasy that somehow became real.",
    "I hope you radiate positivity today, spreading good vibes and beautiful energy to everyone you encounter. You have that power.",
    "You are my heart's keeper, the trusted guardian of my most precious treasure—my love for you.",
    "May your day be as unique and special as you are. There's no one quite like you, and that makes you extraordinary.",
    "You are the love I sought my entire life without even knowing I was searching. And then I found you, and everything made sense.",
    "I hope you feel grounded and centered today, connected to yourself and to what truly matters in your life.",
    "You are my gentle strength, the soft power that holds me up, supports me, and makes me stronger than I could ever be alone.",
    "May your day be full of creative sparks and inspired moments. Let your imagination soar and create something beautiful today.",
    "You are the light in my eyes, the sparkle that brings brightness to my vision of the world. You help me see beauty everywhere.",
    "I hope if it storms today, you dance in the rain and find joy even in the unexpected. You make everything an adventure.",
    "You are my peaceful harbor, the safe port I sail to when the seas of life get rough and turbulent.",
    "May your day be filled with genuine kindness from others and opportunities for you to show your beautiful, compassionate heart.",
    "You are the reason I dare to dream bigger, reach higher, and believe that anything is possible. You inspire my wildest dreams.",
    "I hope you feel absolutely unstoppable today, like you can conquer anything that comes your way. Because you can, my strong girl.",
    "You are my quiet joy, the gentle happiness that doesn't need to shout to be felt deeply and completely.",
    "May your day be as refreshing as morning dew, bringing new life, new energy, and renewed hope to everything you touch.",
    "You are my sweet melody, the song my soul hums throughout the day. You are the music that makes my life beautiful.",
    "I hope you find treasure in the mundane today—discovering magic in ordinary moments, joy in simple things.",
    "You are the answer to prayers I didn't even know I was praying. You are my unexpected blessing, my divine gift.",
    "May your day be painted in bright, vibrant colors—full of life, energy, passion, and all the things that make existence beautiful.",
    "You are my breath of fresh air, the clean, crisp clarity that fills my lungs and makes me feel alive and renewed.",
    "I hope you feel deeply, profoundly, completely loved today. Because you are loved more than words could ever express.",
    "You are my morning sun, rising each day to warm my heart and light my path. You are my constant dawn.",
    "May your day be filled with good news and positive developments. I'm hoping the universe sends wonderful things your way today.",
    "You are my lovely day personified—beautiful, bright, full of promise and joy. You make every day lovely just by being in it.",
    "I hope you attain every goal you set for yourself today. I believe in your abilities and your determination completely.",
    "You are the smile of my heart—the deep, internal joy that radiates from within and colors everything I do.",
    "May your day be smooth sailing, free of obstacles and complications. May everything flow easily and naturally for you.",
    "You are my sweet serenity, the calm that washes over me and makes everything feel peaceful and right.",
    "I hope you feel the gentle embrace of the morning wrapping around you like a warm hug, comforting and loving.",
    "You are the love of my soul, the deepest connection I've ever known. Our souls speak to each other in ways words never could.",
    "May your day be filled with warm moments that heat your heart and remind you of all the love surrounding you.",
    "You are my quiet confidence, the inner strength I draw upon, the faith in myself that you help me cultivate.",
    "I hope you bloom exactly where you're planted today, making the best of your circumstances and growing beautifully.",
    "You are the song of my life, the soundtrack that plays through my days, making every moment more meaningful and beautiful.",
    "May your day be as strong and invigorating as your morning coffee, giving you energy and clarity for whatever lies ahead.",
    "You are my sweet delight, the treat that makes every day special, the indulgence that never feels guilty—only joyful.",
    "I hope you find peace in the chaos today, quiet moments of calm even when everything around you is busy and loud.",
    "You are the light I follow when I'm lost, the beacon that always guides me back to where I need to be.",
    "May your day be filled with clear blue skies, both literally and metaphorically. May obstacles clear and your path be visible.",
    "You are my happy thought, the one I turn to when I need an instant smile, an immediate mood lift, a burst of joy.",
    "I hope you feel the warmth of genuine friendship today. May you be surrounded by people who truly care about you and value you.",
    "You are the beauty of my world, the aesthetic perfection that makes everything more pleasing to look at, to experience, to live.",
    "May your day be as inspiring as you are to me. May you motivate others the way you motivate me every single day.",
    "You are my morning miracle, the wonder that greets me each day and reminds me that life is full of beautiful impossibilities.",
    "I hope you find joy in the journey today, not just in reaching destinations but in every step you take along the way.",
    "You are the love that stays, the constant in my ever-changing world, the stable force I can always count on.",
    "May your day be filled with sweet harmonies—moments that flow together perfectly, creating a beautiful symphony of experiences.",
    "You are my steady hand when mine trembles, the firm grip that keeps me from falling when I feel weak.",
    "I hope you feel the magic inherent in a new day—the fresh start, the clean slate, the infinite possibilities.",
    "You are my cherished one, the person I hold most dear, the treasure I guard with my whole heart and soul.",
    "May your day be as expansive as the sea, full of depth, mystery, beauty, and endless possibilities to explore.",
    "You are my sweet sunshine, the warmth that never fails to brighten my day and melt away any coldness or darkness.",
    "I hope you walk with purpose today, knowing exactly where you're going and why, confident in your direction and choices.",
    "You are the joy in my step, the bounce that makes me move through life with energy and enthusiasm.",
    "May your day be filled with abundant light and overflowing love. May both illuminate your path and warm your heart.",
    "You are my heart's rhythm, the steady beat that keeps everything functioning, the pulse that gives life to my existence.",
    "I hope you feel the earth supportive beneath your feet today, solid and stable, holding you up as you move forward.",
    "You are my sweet morning, the gentle awakening, the soft beginning to every perfect day. You make mornings beautiful.",
    "May your day be as gentle and peaceful as a dove, moving through the hours with grace and tranquility.",
    "You are the love of my days—every single one of them. Each day is better, brighter, more meaningful because of you.",
    "I hope you find moments of stillness today, pockets of quiet where you can simply be, breathe, and exist peacefully.",
    "You are my endless joy, the happiness that never runs dry, the well of delight I can always draw from.",
    "May your day be filled with happy thoughts that lift your spirit and keep a smile on your beautiful face.",
    "You are my sweet refuge, the shelter I seek when I need safety, comfort, and unconditional acceptance.",
    "I hope you feel the gentle embrace of the wind today, carrying my love to you across any distance between us.",
    "You are the star of my show, the main character in my life's story, the protagonist I'm rooting for every single day.",
    "May your day be as bright and promising as your incredible potential. The sky is not the limit—you have no limits.",
    "You are my heart's echo, the sound that reverberates through my being, the voice I hear in every heartbeat.",
    "I hope you feel the pulse of life today—the energy, the vitality, the excitement of being alive and present.",
    "You are my sweet escape, my vacation from reality, my perfect getaway even when we're right here in the everyday.",
    "May your day be filled with little luxuries—small indulgences that make you feel special, pampered, and valued.",
    "You are the love I breathe, as essential to me as oxygen, as necessary for my survival, as vital to my existence.",
    "I hope you find clarity even in the clouds today, seeing through any confusion to the truth underneath.",
    "You are my morning dew, the fresh, sparkling start to each day, the crystalline promise of new beginnings.",
    "May your day be as solid and dependable as a rock, giving you the stability and foundation you need.",
    "You are my sweet melody, the tune that plays in my head and heart, making everything more musical and harmonious.",
    "I hope you feel the rhythm of life today—whether it's the city's energy or nature's peace. Let it move you.",
    "You are the love I keep safe in my heart, protected, treasured, and never taken for granted.",
    "May your day be filled with honest moments—genuine connections, authentic experiences, and real, true feelings.",
    "You are my bright horizon, the promise of beautiful things ahead, the view I'm always looking forward to.",
    "I hope you feel the strength of mountains today, immovable and powerful, able to withstand anything that comes your way.",
    "You are my sweet sensation, the feeling that makes everything tingle with excitement and possibility.",
    "May your day flow like a river—smoothly, naturally, finding its way around obstacles, always moving forward.",
    "You are the love I found when I stopped looking, the surprise that became the best thing that ever happened to me.",
    "I hope you find warmth even in the coldest moments today. May you always have something to warm your heart.",
    "You are my faithful heart, the loyal love that never wavers, never doubts, never gives up on us.",
    "May your day be filled with quiet confidence—the kind that doesn't need to be loud to be powerful and effective."
]

final_quotes = []

# First pass: 1 to 322
for i, msg in enumerate(messages):
    final_quotes.append({
        "id": i + 1,
        "text": prefix + msg + suffix
    })

# Second pass: 323 to 644 (repeat)
for i, msg in enumerate(messages):
    final_quotes.append({
        "id": i + 1 + len(messages),
        "text": prefix + msg + suffix
    })

with open('c:/Users/user/Desktop/rashi3/data/quotes.json', 'w', encoding='utf-8') as f:
    json.dump(final_quotes, f, indent=4)

print(f"Successfully wrote {len(final_quotes)} quotes to data/quotes.json")
